config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do 
    resources :favorites, only: [:index]
    resources :relationships, only: [:create, :destroy]
    get :follows, on: :member 
    get :followers, on: :member 
  end
  resources :favorites, only: [:create, :destroy]
 mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user 
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates  :content, presence: true, length: {in: 1..140}
    validates :image, presence: true
    belongs_to :user 
    has_many :favorites, dependent: :destroy 
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30}
    validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: true
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    mount_uploader :icon, IconUploader
    has_many :posts
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post
    has_many :active_relationships, class_name: "Relationship",foreign_key: :following_id
    has_many :followings, through: :active_relationships, source: :follower 
    has_many :passive_relationships, class_name: "Relationship",foreign_key: :follower_id
    has_many :followers, through: :passive_relationships, source: :following
    
    def followed_by?(user)
      passive_relationships.find_by(following_id: user.id).present? 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def index 
      @user=User.find(params[:user_id])
      @favorite_posts=@user.favorite_posts
    end
    def create 
      favorite = current_user.favorites.create(post_id: params[:post_id])
      redirect_to posts_url, notice: "#{favorite.post.user.name}さんのブログをお気に入り登録しました"
    end 
    def destroy 
      favorite = current_user.favorites.find_by(id: params[:id]).destroy
      redirect_to posts_url, notice: "#{favorite.post.user.name}さんのブログをお気に入り解除しました"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  before_action :login_user, only:[:new, :show, :edit,:destroy]
  before_action :edit_userpost, only:[:edit, :destroy]
  def index
    @posts=Post.all.includes(:user).order(created_at: :desc)
  end

  def new
    @post=if params[:back]
            Post.new(post_params)
          else
            Post.new
          end
  end
  def create 
    @post=current_user.posts.build(post_params)
    
    if @post.save 
      PostMailer.post_mailer(@post).deliver
      redirect_to posts_path 
    else 
      render 'new'
    end
  end

  def show
  end

  def edit
  end 
  def update 
    if @post.update(post_params)
      redirect_to posts_path 
    else 
      render "edit" 
    end
  end 
  def destroy 
    @post.destroy 
    redirect_to posts_path
  end
  def confirm
    @post=Post.new(post_params)
    @post.user_id = current_user.id 
    render :new if @post.invalid?
  end
  
  private
  
  def post_params 
    params.require(:post).permit(:content, :image,:image_cache )
  end
  def set_post 
    @post=Post.find(params[:id])
  end
  def login_user
    if current_user.nil? 
      flash[:notice]="ログインしてください"
      redirect_to new_session_path
    end
  end
  def edit_userpost
    if @post.user_id != current_user.id 
      flash[:notice]="権限がありません"
      redirect_to posts_path 
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end 
  def create 
    user=User.find_by(email: params[:session][:email].downcase) 
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      redirect_to user_path(user.id)
    else 
      flash.now[:danger]="ログインに失敗しました"
      render "new"
    end
  end 
  def destroy 
    session.delete(:user_id)
    flash[:notice]="ログアウトしました"
    redirect_to new_session_path
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  before_action :edit_userpost, only:[:edit]
  def new
    @user=User.new
  end
 
  def create 
    @user=User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  def show 
  end

  def edit
    
  end 
  def update 
    if @user.update(user_params)
      redirect_to user_path(@user) 
    else 
      render "edit" 
    end
  end
  private 
  def user_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache, :bio)
  end
  def set_user 
    @user=User.find(params[:id])
  end
 
  def edit_userpost
    if @user.id != current_user.id 
      flash[:notice]="権限がありません"
      redirect_to posts_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
      if action_name == "new" || action_name == "confirm"
        confirm_posts_path
      elsif action_name == "edit"
        post_path
      end
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user 
        @current_user ||=User.find_by(id: session[:user_id])
    end
    def logged_in? 
        current_user.present? 
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_errors.html.erb
<% if obj.errors.any? %> 
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this object from being saved:</h2>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash.html.erb
<div class="error_message">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key} alert alert-info") %>
  <% end %>
</div>

app/views/favorites/index.html.erb
<div class="container"> 
  <div class="row">
    <% if @favorite_posts.present? %>
    <% @favorite_posts.each do |favorite_posts| %>
    <div class="col-md-4">
      <div class="card">
        <%= image_tag(favorite_posts.image.medium.url,class:"card-img")%>
        <div class="card-body">
          <h5><p>投稿者: <%= favorite_posts.user.name %></p></h5>
          <p class="card-text"><%= favorite_posts.content %></p>
        </div>
      </div> 
    </div>
    <% end %>
    <% else %> 
     <h2>お気に入りはまだありません。</h2>
  
    <% end %> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Instagram Clone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <%= link_to "投稿", new_post_path, class: "btn btn-primary nav-link" %>
            </li> 
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path,class:"nav-link" %>
            </li>
             <li class="nav-item">
              <%= link_to "お気に入り", user_favorites_path(current_user.id),class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Profile", user_path(current_user.id) , class:"nav-link" %>
           </li>
           <li class="nav-item">
             <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"nav-link"  %>
           </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
    
    <%= render 'flash' %>
    
    <%= yield %> 
    
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container col-md-offset-3 col-md-6 header">
<div class="card">
  <h3 class="card-header">新規投稿</h3>
  <div class="card-body">
    <%= form_with(model: @post, local: true,url: choose_new_or_edit) do |f| %>
     <%= render "errors", obj: f.object %>
    <div class="form-group">
    <%= f.label :画像 %>
    <%= f.file_field :image, class:"form-control"%>
    <%= f.hidden_field :image_cache %>
    </div>
    <div class="form-group">
    <%= f.label :コメント %>
    <%= f.text_area :content, class:"form-control"%>
    </div>
    <%= f.submit "投稿", class:"btn btn-primary" %>
    </div>
    <% end %>
</div>
</div>
</div>

app/views/posts/confirm.html.erb
<div class="col-md-6 offset-md-3 header">
<h3>以下の内容で投稿してもよろしいですか？</h3>
<hr> 
<div class="card">
  <%= image_tag(@post.image.medium.url,class:"card-img") %>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %> 
  <%= form.hidden_field :image_cache %> 
  <%= form.text_area :content, class: 'form-control', readonly: "readonly" %>
  <%= form.hidden_field :content %>
  <%= form.submit "投稿", class: "btn btn-primary"%>
<% end %>  
</div>

<%= form_with(model: @post, url:new_post_path, local: true, method:"get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %> 
<% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="container col-md-offset-3 col-md-6 header">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center">
          <%= link_to user_path(post.user_id), class: "no-text-decoration" do %>
            <strong><%= post.user.name %></strong>
          <% end %>
        </div>
        <%= link_to post_path(post.id) do %>
          <%= image_tag post.image.url(:medium), class: "card-img" %>
        <% end %>
        <div class="card-body">
          <div><%= post.content %></div>
          <% @favorite = current_user.favorites.find_by(post_id: post.id) if logged_in? %>
          <div class="row parts">
            <% if @favorite.present? %>
            <%= link_to "お気に入り解除",favorite_path(id: @favorite.id),method: :delete,class: "btn btn-danger" %>
            <% else %>
            <%= link_to "お気に入り",favorites_path(post_id: post.id), method: :post,class:'btn btn-primary' %>
            <% end %>
          </div>
          <div> 
            <strong>「いいね！」<%= post.favorite_users.count %>件</strong>
          </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", "#", class: "post-time no-text-decoration" %>
            <hr>
            <div class="row parts">
              <form action="#" class="w-100">
                <div>
                  <textarea class="form-control comment-input border-0" placeholder="コメント..." rows="1"></textarea>
                </div>
              </form>
            </div>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%=render 'form' %>

app/views/posts/show.html.erb
<div class="container header">
  <div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.image.medium.url, class: "card-img" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user_id), class: "black-color no-text-decoration",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to edit_post_path(@post.id),class: "icon" do %>
                <i class="fas fa-cog text-dark"></i>
              <% end %>
              <%= link_to post_path(@post.id), method: :delete, data: {confirm: '本当に削除していいですか'},class: "icon"  do %>
                <i class="fas fa-trash-alt text-dark"></i>
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.content %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
            </div>
          </div>
        </div>
        <div class="row parts">
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
      </div>
    </div>
  </div>
</div>
</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="container col-md-offset-3 col-md-6 header">
<div class="profile-form-wrap">
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :icon, "プロフィール画像" %>
      <%= f.file_field :icon, autofocus: true,class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name, "名前" %>
      <%= f.text_field :name, autofocus: true,class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :bio, "プロフィール" %>
      <%= f.text_area :bio, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, autofocus: "off", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation, autofocus: "off", class: "form-control" %>
    </div>
      <%= f.submit "変更する", class: "btn btn-primary" %>
  <% end %>
</div>      
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row">  
    <div class="col-md-7 d-none d-md-block top-image">
      <%= image_tag "/assets/beach.jpg", class:"menu-image" %>
    </div>  
    <div class="col-md-5 sign">
        <div class="sign-name">
          <h2>Instagram Clone</h2> 
          <p>登録して画像を共有しよう</p>
        </div>
      <%= form_with(model: @user, local: true ) do |f| %> 
        <%= render "errors", obj: f.object %>
        <div class="form-group">
          <%= f.text_field :name, class:"form-control", placeholder:"名前"%>
        </div>
        <div class="form-group">
          <%= f.email_field :email, class:"form-control" , placeholder:"メールアドレス"%>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class:"form-control", placeholder:"パスワード" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, class:"form-control",  placeholder:"パスワード確認" %>
        </div>
        <div>
          <label for="file_photo">
            ＋プロフィール画像を選択
            <%= image_tag(@user.icon.url) if @user.icon.url %>
            <%= f.file_field :icon,id:"file_photo",style:"display:none;"%>
          </label>
        </div>
        <div class="form-group">
          <%= f.submit "登録", class: "btn btn-primary btn-lg btn-block" %>
        </div>
        <%= link_to "アカウントをお持ちですか？",new_session_path %>
        <% end %> 
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class=" col-md-8 col-md-offset2 mx-auto user-content">
  <div class="user-profile">
    <%= image_tag @user.icon, class:"card-img-top" %>
    <div class="user-body"> 
      <ul>
        <li class="user-title"><%= @user.name %></li>
        <% if @user.id == current_user.id %>
        <li class="user-btn"><%= link_to "設定",edit_user_path(@user.id),class:"btn btn-primary btn-round " %></li>
        <% end %>
      </ul> 
    </div> 
    <div class="user-bio">
      <p ><%= @user.bio %></p>
    </div>
  </div>
</div>